const NAME_MAX_LENGTH = 30;
const PASSWORD_MIN_LENGTH = 6;
const PASSWORD_MAX_LENGTH = 40;
const MIN_MONTH_DAY = 1;
const MAX_MONTH_DAY = 31;
const MIN_MONTH = 1;
const MAX_MONTH = 12;
const MAX_AGE = 200;

module.exports = {
  NAME_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  PASSWORD_MAX_LENGTH,
  MIN_MONTH_DAY,
  MAX_MONTH_DAY,
  MIN_MONTH,
  MAX_MONTH,
  MAX_AGE,
};
